### ISSUE TITLE
Revert the no-op workaround due to upstream fixes?

### ISSUE THREAD

**Issue by Onkelborg** [aligent/owasp-dependency-check-pipe#23]
Hi

Would it be possible to revert the no-op workaround now? I think that it should have been fixed in upstream now with the release of dependency check 10.0.0/10.0.1?

* Changelog: https://github.com/jeremylong/DependencyCheck/blob/main/CHANGELOG.md
* Upstream docker image: https://hub.docker.com/r/owasp/dependency-check/tags - this was pushed ~12 hours after the no-op workaround here was implemented

/Oskar

**Comment by AdamJHall** [comment]
Sure thing, will be reverted with [PR](https://github.com/aligent/owasp-dependency-check-pipe/pull/24)
